MotionSensorServer/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sensors/reading/(?P<custom_id>[0-9]+)/(?P<is_motion_detected>[0-1])', views.reading, name='reading'),
    url(r'^new_sensor/', views.new_sensor, name='new_sensor'),
    url(r'^(?P<sensor_id>[0-9]+)/remove/', views.remove_sensor, name='remove_sensor'),
    url(r'^sensors/$', views.get_sensors, name='sensors'),
    url(r'^detections/(?P<sensor_id>[0-9]+)', views.get_detections_per_sensor, name='detections_sensor'),
    url(r'^detections/', views.get_detections_per_user, name='detections_user'),
    url(r'^sensors/(?P<sensor_id>[0-9]+)/switch_sensor_state/', views.switch_sensor_state, name='switch_sensor_state'),
]

sw_repo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('MotionSensorServer.urls', namespace='MotionSensorServer'), name='main'),
    url(r'^admin/', admin.site.urls),
    url(r'^motion/', include('MotionSensorServer.urls', namespace='MotionSensorServer'), name='main'),
    url(r'^accounts/', include('registration.urls'))
]

MotionSensorServer/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.forms import ModelForm


class Sensor(models.Model):
    name = models.CharField(max_length=100)
    custom_id = models.CharField(null=False, unique=True, max_length=10)
    activated = models.BooleanField()


class SensorReading(models.Model):
    sensor = models.ForeignKey(Sensor, null=False)
    date_from = models.DateTimeField(null=False)
    date_to = models.DateTimeField(null=False)
    detected = models.BooleanField(default=False)


class UserSensor(models.Model):
    user = models.ForeignKey(User)
    sensor = models.ForeignKey(Sensor)


class SensorForm(ModelForm):
    class Meta:
        model = Sensor
        fields = ['name', 'custom_id', 'activated']

MotionSensorServer/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from MotionSensorServer.models import Sensor, SensorReading, SensorForm, UserSensor
from django.utils import timezone
from django.core.urlresolvers import reverse


def index(request):
    return render_to_response("MotionSensorServer/index.html", {
        'user': request.user,
    }, RequestContext(request))


@require_http_methods(["POST"])
@csrf_exempt
def reading(request, custom_id, is_motion_detected):
    motion_detected = (is_motion_detected == '1')

    if Sensor.objects.filter(custom_id=custom_id).exists():

        create_new = False

        sensor = Sensor.objects.get(custom_id=custom_id)
        if sensor.activated:

            if SensorReading.objects.filter(sensor=sensor).exists():
                last_reading = SensorReading.objects.filter(sensor=sensor).latest('date_from')

                last_reading.date_to = timezone.now()
                last_reading.save()

                create_new = (last_reading.detected != motion_detected)
            else:
                create_new = True

            if create_new:
                sensor_reading = SensorReading(
                    sensor=sensor,
                    date_from=timezone.now(),
                    date_to=timezone.now(),
                    detected=motion_detected)

                sensor_reading.save()

    return HttpResponse('')


@login_required()
def new_sensor(request):
    if request.method == 'POST':
        form = SensorForm(request.POST)
        if form.is_valid():
            try:
                my_new_sensor = form.save()
                UserSensor.objects.get_or_create(user=request.user, sensor=my_new_sensor)
                return HttpResponseRedirect(reverse('MotionSensorServer:sensors'))
            except:
                pass
    return render_to_response('MotionSensorServer/new_sensor.html', {'form': SensorForm()},
                              context_instance=RequestContext(request))


@login_required()
def get_sensors(request):
    user_sensors = [i.sensor for i in UserSensor.objects.filter(user__exact=request.user)]

    return render_to_response('MotionSensorServer/sensors.html', {
        "items": user_sensors
    }, RequestContext(request))


@login_required()
def get_detections_per_user(request):
    user_sensors = [i.sensor for i in UserSensor.objects.filter(user__exact=request.user)]
    detections = SensorReading.objects.order_by("-date_from")
    detections = [i for i in detections if i.sensor in user_sensors]
    return render_to_response('MotionSensorServer/detections.html', {
        "items": detections
    }, RequestContext(request))


@login_required()
def get_detections_per_sensor(request, sensor_id):
    detections = SensorReading.objects.filter(sensor__exact=sensor_id).order_by("-date_from")
    return render_to_response('MotionSensorServer/detections.html', {
        "items": detections
    }, RequestContext(request))


@login_required
def remove_sensor(request, sensor_id):
    sensor_r = get_object_or_404(Sensor, pk=sensor_id)
    sensor_r.delete()
    return HttpResponseRedirect(reverse('MotionSensorServer:sensors'))


@login_required
def switch_sensor_state(request, sensor_id):
    sensor_r = get_object_or_404(Sensor, pk=sensor_id)

    if sensor_r.activated:
        sensor_r.activated = False
    else:
        sensor_r.activated = True

    sensor_r.save()

    return HttpResponseRedirect(reverse('MotionSensorServer:sensors'))

MotionSensorServer/templates/MotionSensorServer/detections.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Sensors{% endblock %}

{% block content %}
<div class="text-center">
    <H1>Detections</H1>
</div>
<table class="table">
    <tr>
        <th>Sensor id</th>
        <th>Sensor name</th>
        <th>First measurement</th>
        <th>Last measurement</th>
        <th>Detected</th>
    </tr>
    {% for item in items %}
    <tr>
        <td>{{ item.sensor.id }}</td>
        <td>{{ item.sensor.name }}</td>
        <td>{{ item.date_from }}</td>
        <td>{{ item.date_to }}</td>
        <td>{{ item.detected }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

MotionSensorServer/templates/MotionSensorServer/index.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Sensors{% endblock %}

{% block content %}
<div class="text-center">
    <H1>Welcome</H1>
</div>
{% endblock %}

MotionSensorServer/templates/MotionSensorServer/new_sensor.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}New Sensor{% endblock %}

{% block content %}
<div class="text-center">
    <H1>New Sensor</H1>

    <div class="form">
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>ID:</label>
                <br>
                {{ form.custom_id}}
            </div>
            <div class="form-group">
                <label>Name:</label>
                <br>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label>Activated:</label>
                <br>
                {{ form.activated }}
            </div>
            <input type="submit" value="Save"/>
            <input type="hidden" name="next" value="{{ next }}"/>
        </form>
    </div>
</div>
{% endblock %}

MotionSensorServer/templates/MotionSensorServer/sensors.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Sensors{% endblock %}

{% block content %}
<div class="text-center">
    <H1>Sensors</H1>
</div>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Activated</th>
        <th>Actions</th>
    </tr>
    {% for item in items %}
    <tr>
        <td>{{ item.custom_id }}</td>
        <td>{{ item.name }}</td>
        <td>{{ item.activated }}</td>
        <td>

            <p>
                <a class="c_href" href="{% url 'MotionSensorServer:remove_sensor' item.id %}"
                   onclick="return confirm('Are you sure you want to delete this sensor?')">Delete</a>

                <a class="c_href" href="{% url 'MotionSensorServer:detections_sensor' item.id %}">Detections</a>

                {% if item.activated %}
                <a class="c_href" href="{% url 'MotionSensorServer:switch_sensor_state' item.id %}"
                   onclick="return confirm('Are you sure you want to deactivate this sensor?')">Deactivate</a>
                {% else %}
                <a class="c_href" href="{% url 'MotionSensorServer:switch_sensor_state' item.id %}"
                   onclick="return confirm('Are you sure you want to activate this sensor?')">Activate</a>
                {% endif %}
            </p>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

MotionSensorServer/templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Motion Sensor Server{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'MotionSensorServer/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'MotionSensorServer/css/customizations.css' %}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'MotionSensorServer/js/bootstrap.min.js' %}"></script>
<div id="content">

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'MotionSensorServer:index' %}">Home</a>
                {% if user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'MotionSensorServer:new_sensor' %}">Add Sensor</a>
                <a class="navbar-brand" href="{% url 'MotionSensorServer:sensors' %}">Sensors</a>
                <a class="navbar-brand" href="{% url 'MotionSensorServer:detections_user' %}">Detections</a>
                {% endif %}
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                {% if user.is_authenticated %}
                <p class="navbar-text">
                    Hello
                    {{ user.username }}
                </p>
                {% else %}
                <p class="navbar-text">Hello</p>
                {% endif %}
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                    <li><a href="{% url 'auth_password_change' %}">Password change</a></li>
                    {% else %}
                    <li><a href="{% url 'auth_login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    {% block content %}
    {% endblock %}
</div>

<div id="footer">
    {% block footer %}
    <hr/>
    <div class="text-center">
        <p>Authors: Sebastian Pawlak, Łukasz Kosiak</p>
    </div>
    {% endblock %}
</div>
</body>
</html>